#
# Copyright (C) 2008 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk
include $(INCLUDE_DIR)/kernel.mk

PKG_NAME:=Probe-Module
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk
define KernelPackage/Probe-Module
SUBMENU:=Other modules
TITLE:=Something description for your module
FILES:=$(PKG_BUILD_DIR)/Probe-Module.ko
AUTOLOAD:=$(call AutoLoad,10,Probe-Module)
endef

MAKE_OPTS:= \
	ARCH="$(LINUX_KARCH)" \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	SUBDIRS="$(PKG_BUILD_DIR)"

define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)
	$(CP) ./src/* $(PKG_BUILD_DIR)/
endef

define Build/Compile
	$(MAKE) -C "$(LINUX_DIR)" \
		$(MAKE_OPTS) \
		modules
endef

$(eval $(call KernelPackage,Probe-Module))
